console.log(`Day 16`);

const day16Arr = [
    {cars: 9, akitas: 3, goldfish: 0},
    {akitas: 9, children: 3, samoyeds: 9},
    {trees: 6, cars: 6, children: 4},
    {trees: 4, vizslas: 4, goldfish: 9},
    {akitas: 9, vizslas: 7, cars: 5},
    {vizslas: 6, goldfish: 6, akitas: 3},
    {pomeranians: 5, samoyeds: 0, perfumes: 10},
    {cars: 10, pomeranians: 7, goldfish: 8},
    {trees: 2, vizslas: 7, samoyeds: 6},
    {perfumes: 5, pomeranians: 4, children: 9},
    {vizslas: 5, perfumes: 8, cars: 10},
    {children: 10, cars: 6, perfumes: 5},
    {cats: 4, samoyeds: 7, pomeranians: 8},
    {perfumes: 6, goldfish: 10, children: 7},
    {perfumes: 4, pomeranians: 3, cars: 6},
    {perfumes: 7, cars: 9, pomeranians: 6},
    {goldfish: 3, cars: 6, vizslas: 7},
    {perfumes: 6, cars: 7, goldfish: 3},
    {trees: 0, akitas: 3, pomeranians: 8},
    {goldfish: 6, trees: 2, akitas: 6},
    {pomeranians: 9, akitas: 9, samoyeds: 9},
    {vizslas: 2, cars: 9, perfumes: 5},
    {goldfish: 10, samoyeds: 8, children: 9},
    {akitas: 4, goldfish: 1, vizslas: 5},
    {goldfish: 10, trees: 8, perfumes: 6},
    {vizslas: 5, akitas: 8, trees: 1},
    {trees: 3, cars: 6, perfumes: 2},
    {goldfish: 8, trees: 7, akitas: 10},
    {children: 5, trees: 1, goldfish: 10},
    {vizslas: 3, perfumes: 8, akitas: 3},
    {cars: 6, children: 10, perfumes: 7},
    {cars: 10, perfumes: 3, goldfish: 10},
    {perfumes: 9, vizslas: 3, akitas: 4},
    {perfumes: 10, vizslas: 7, children: 8},
    {cars: 5, perfumes: 5, vizslas: 9},
    {trees: 9, cars: 9, akitas: 7},
    {samoyeds: 9, perfumes: 2, cars: 10},
    {akitas: 7, cars: 5, trees: 5},
    {goldfish: 8, trees: 9, cars: 10},
    {trees: 0, cats: 1, pomeranians: 1},
    {pomeranians: 6, perfumes: 9, samoyeds: 1},
    {vizslas: 6, akitas: 3, pomeranians: 1},
    {vizslas: 2, perfumes: 3, pomeranians: 6},
    {akitas: 5, pomeranians: 0, vizslas: 10},
    {vizslas: 4, goldfish: 1, cars: 5},
    {cars: 4, vizslas: 8, cats: 0},
    {cats: 5, children: 8, pomeranians: 2},
    {vizslas: 3, perfumes: 6, cats: 0},
    {akitas: 7, perfumes: 0, trees: 7},
    {trees: 4, akitas: 10, vizslas: 2},
    {goldfish: 10, cars: 9, trees: 4},
    {cars: 5, children: 9, perfumes: 0},
    {vizslas: 5, cars: 3, cats: 8},
    {cars: 5, akitas: 1, goldfish: 10},
    {akitas: 10, vizslas: 2, cars: 6},
    {cats: 6, trees: 0, cars: 4},
    {vizslas: 1, akitas: 1, samoyeds: 7},
    {samoyeds: 6, vizslas: 1, akitas: 7},
    {akitas: 9, cars: 8, vizslas: 1},
    {cars: 6, vizslas: 7, goldfish: 0},
    {pomeranians: 5, akitas: 6, vizslas: 2},
    {samoyeds: 2, cats: 8, goldfish: 7},
    {vizslas: 10, goldfish: 7, samoyeds: 9},
    {perfumes: 2, trees: 1, akitas: 6},
    {cars: 8, perfumes: 10, vizslas: 9},
    {akitas: 8, vizslas: 8, perfumes: 8},
    {goldfish: 7, cars: 9, samoyeds: 9},
    {perfumes: 2, children: 7, akitas: 1},
    {perfumes: 7, vizslas: 9, akitas: 1},
    {samoyeds: 3, vizslas: 1, trees: 1},
    {vizslas: 8, goldfish: 7, trees: 9},
    {goldfish: 8, cars: 6, trees: 9},
    {perfumes: 5, cars: 10, samoyeds: 7},
    {pomeranians: 4, perfumes: 3, cars: 5},
    {samoyeds: 1, perfumes: 1, pomeranians: 1},
    {goldfish: 4, cats: 6, akitas: 7},
    {perfumes: 5, akitas: 4, vizslas: 8},
    {perfumes: 4, cats: 3, children: 4},
    {vizslas: 5, pomeranians: 9, samoyeds: 7},
    {cars: 3, samoyeds: 5, pomeranians: 7},
    {vizslas: 2, samoyeds: 4, perfumes: 2},
    {trees: 1, akitas: 10, vizslas: 9},
    {vizslas: 0, akitas: 2, samoyeds: 5},
    {perfumes: 5, vizslas: 7, children: 8},
    {cats: 3, children: 2, trees: 0},
    {cars: 3, perfumes: 2, goldfish: 2},
    {trees: 1, akitas: 7, vizslas: 0},
    {trees: 1, akitas: 2, samoyeds: 1},
    {cars: 4, vizslas: 8, akitas: 1},
    {perfumes: 5, cats: 3, vizslas: 0},
    {samoyeds: 7, cats: 6, goldfish: 8},
    {samoyeds: 10, cats: 0, cars: 7},
    {cars: 6, akitas: 7, samoyeds: 2},
    {perfumes: 0, goldfish: 6, trees: 9},
    {cars: 6, pomeranians: 2, samoyeds: 8},
    {cars: 2, trees: 9, samoyeds: 4},
    {goldfish: 5, trees: 1, children: 0},
    {akitas: 9, goldfish: 7, children: 6},
    {goldfish: 9, akitas: 0, pomeranians: 0},
    {samoyeds: 6, children: 8, vizslas: 5},
    {vizslas: 6, cars: 5, goldfish: 4},
    {vizslas: 6, akitas: 2, perfumes: 6},
    {samoyeds: 3, akitas: 7, children: 4},
    {cars: 3, perfumes: 10, cats: 6},
    {vizslas: 9, pomeranians: 0, cars: 1},
    {cats: 6, samoyeds: 8, pomeranians: 5},
    {cars: 7, trees: 4, akitas: 10},
    {perfumes: 3, vizslas: 1, goldfish: 9},
    {trees: 6, cars: 8, goldfish: 5},
    {pomeranians: 2, children: 1, vizslas: 7},
    {akitas: 0, vizslas: 8, cars: 0},
    {goldfish: 3, vizslas: 6, akitas: 2},
    {akitas: 10, pomeranians: 7, perfumes: 7},
    {cars: 10, cats: 2, vizslas: 8},
    {akitas: 8, trees: 1, vizslas: 2},
    {vizslas: 2, akitas: 7, perfumes: 1},
    {goldfish: 0, vizslas: 10, trees: 9},
    {trees: 3, cars: 0, goldfish: 0},
    {perfumes: 7, goldfish: 5, trees: 9},
    {children: 9, vizslas: 3, trees: 5},
    {vizslas: 1, goldfish: 7, akitas: 10},
    {perfumes: 1, cars: 6, trees: 1},
    {akitas: 2, vizslas: 0, goldfish: 7},
    {vizslas: 10, pomeranians: 7, akitas: 0},
    {perfumes: 4, cats: 5, vizslas: 2},
    {cars: 6, samoyeds: 8, akitas: 3},
    {trees: 9, goldfish: 7, akitas: 9},
    {cars: 8, trees: 0, perfumes: 2},
    {pomeranians: 7, vizslas: 2, perfumes: 6},
    {vizslas: 9, pomeranians: 3, trees: 6},
    {vizslas: 7, cars: 9, perfumes: 1},
    {akitas: 2, pomeranians: 9, vizslas: 7},
    {trees: 9, pomeranians: 10, samoyeds: 0},
    {children: 4, akitas: 10, perfumes: 4},
    {vizslas: 1, cats: 1, trees: 8},
    {samoyeds: 7, cars: 8, goldfish: 5},
    {perfumes: 0, children: 1, pomeranians: 10},
    {vizslas: 4, perfumes: 5, cars: 5},
    {trees: 2, perfumes: 8, goldfish: 0},
    {cars: 10, akitas: 5, goldfish: 7},
    {children: 4, trees: 3, goldfish: 8},
    {cars: 8, perfumes: 6, trees: 7},
    {akitas: 6, goldfish: 0, trees: 10},
    {akitas: 7, pomeranians: 10, perfumes: 10},
    {trees: 10, vizslas: 3, goldfish: 4},
    {samoyeds: 4, akitas: 3, perfumes: 6},
    {akitas: 8, perfumes: 2, pomeranians: 10},
    {cars: 2, perfumes: 0, goldfish: 8},
    {goldfish: 6, akitas: 7, perfumes: 6},
    {cars: 2, pomeranians: 5, perfumes: 4},
    {goldfish: 1, cars: 5, trees: 0},
    {pomeranians: 4, cars: 7, children: 1},
    {goldfish: 8, cars: 1, children: 10},
    {cars: 6, perfumes: 8, trees: 1},
    {akitas: 4, perfumes: 6, pomeranians: 2},
    {pomeranians: 5, cars: 4, akitas: 1},
    {cats: 5, cars: 9, goldfish: 8},
    {vizslas: 5, samoyeds: 1, children: 7},
    {vizslas: 1, perfumes: 3, akitas: 1},
    {goldfish: 10, pomeranians: 9, perfumes: 5},
    {samoyeds: 3, trees: 7, cars: 2},
    {cars: 2, pomeranians: 1, vizslas: 6},
    {vizslas: 3, perfumes: 5, akitas: 6},
    {vizslas: 1, trees: 0, akitas: 5},
    {vizslas: 5, cars: 6, pomeranians: 8},
    {cars: 10, perfumes: 2, trees: 9},
    {cars: 10, pomeranians: 6, perfumes: 4},
    {akitas: 7, trees: 10, goldfish: 7},
    {akitas: 1, perfumes: 10, cars: 10},
    {akitas: 5, samoyeds: 8, vizslas: 6},
    {children: 3, akitas: 2, vizslas: 3},
    {goldfish: 5, vizslas: 5, perfumes: 9},
    {perfumes: 5, goldfish: 10, trees: 5},
    {akitas: 5, vizslas: 2, children: 7},
    {perfumes: 5, cars: 7, samoyeds: 2},
    {cars: 8, vizslas: 10, akitas: 7},
    {perfumes: 7, children: 8, goldfish: 7},
    {cars: 1, pomeranians: 9, samoyeds: 0},
    {perfumes: 6, cars: 2, trees: 6},
    {trees: 3, vizslas: 7, children: 3},
    {vizslas: 8, samoyeds: 2, trees: 9},
    {perfumes: 3, cats: 1, children: 5},
    {akitas: 9, cats: 6, children: 3},
    {pomeranians: 9, cars: 6, perfumes: 8},
    {vizslas: 9, trees: 0, akitas: 9},
    {perfumes: 6, cars: 5, goldfish: 5},
    {perfumes: 4, cats: 7, vizslas: 2},
    {akitas: 7, cars: 4, children: 10},
    {akitas: 0, goldfish: 7, vizslas: 5},
    {akitas: 5, cars: 5, cats: 6},
    {cars: 6, children: 0, perfumes: 3},
    {cats: 2, perfumes: 10, goldfish: 7},
    {trees: 1, perfumes: 0, cars: 8},
    {perfumes: 9, children: 4, cats: 6},
    {akitas: 7, trees: 3, goldfish: 6},
    {goldfish: 8, cars: 8, samoyeds: 0},
    {cats: 0, akitas: 10, vizslas: 0},
    {goldfish: 1, perfumes: 3, cars: 8},
    {akitas: 10, vizslas: 5, samoyeds: 6},
    {pomeranians: 9, goldfish: 9, samoyeds: 7},
    {samoyeds: 0, goldfish: 7, akitas: 6},
    {vizslas: 0, goldfish: 2, akitas: 1},
    {goldfish: 3, children: 0, vizslas: 8},
    {cars: 8, trees: 2, perfumes: 2},
    {cars: 4, perfumes: 5, goldfish: 8},
    {vizslas: 3, trees: 2, akitas: 1},
    {cars: 7, goldfish: 5, trees: 1},
    {goldfish: 1, cars: 6, vizslas: 8},
    {cats: 4, trees: 1, children: 0},
    {cats: 10, children: 0, perfumes: 0},
    {cars: 4, pomeranians: 7, samoyeds: 5},
    {cars: 2, pomeranians: 10, trees: 1},
    {trees: 10, cats: 5, cars: 10},
    {perfumes: 5, trees: 1, vizslas: 1},
    {akitas: 10, vizslas: 8, samoyeds: 8},
    {vizslas: 2, cats: 5, pomeranians: 3},
    {akitas: 10, perfumes: 0, cats: 10},
    {trees: 8, cats: 5, vizslas: 2},
    {goldfish: 10, perfumes: 8, children: 2},
    {samoyeds: 9, trees: 8, vizslas: 7},
    {children: 7, trees: 6, cars: 6},
    {cats: 4, akitas: 5, pomeranians: 0},
    {trees: 8, goldfish: 2, perfumes: 8},
    {pomeranians: 9, cars: 8, akitas: 5},
    {akitas: 10, vizslas: 0, trees: 2},
    {akitas: 8, cats: 6, cars: 7},
    {trees: 1, akitas: 3, goldfish: 4},
    {pomeranians: 6, cats: 3, goldfish: 3},
    {trees: 10, perfumes: 3, vizslas: 7},
    {perfumes: 8, cars: 7, akitas: 0},
    {perfumes: 10, goldfish: 4, cars: 6},
    {goldfish: 7, trees: 3, cats: 2},
    {perfumes: 6, trees: 4, akitas: 4},
    {goldfish: 9, cats: 4, cars: 7},
    {pomeranians: 6, vizslas: 0, akitas: 6},
    {samoyeds: 5, cars: 5, children: 4},
    {vizslas: 10, cars: 4, goldfish: 4},
    {goldfish: 3, samoyeds: 7, akitas: 2},
    {cats: 8, children: 2, vizslas: 7},
    {cars: 9, perfumes: 4, trees: 9},
    {trees: 8, vizslas: 2, goldfish: 5},
    {cars: 6, trees: 3, vizslas: 3},
    {cats: 6, children: 7, cars: 4},
    {cats: 10, perfumes: 2, goldfish: 7},
    {akitas: 8, cats: 10, perfumes: 8},
    {vizslas: 8, akitas: 5, perfumes: 10},
    {goldfish: 2, vizslas: 5, akitas: 7},
    {akitas: 3, perfumes: 0, trees: 10},
    {cats: 4, vizslas: 5, pomeranians: 6},
    {children: 3, vizslas: 7, perfumes: 2},
    {cars: 0, pomeranians: 10, perfumes: 0},
    {akitas: 0, goldfish: 9, cars: 6},
    {perfumes: 7, cars: 4, samoyeds: 5},
    {akitas: 9, trees: 10, cars: 4},
    {samoyeds: 10, children: 6, akitas: 7},
    {trees: 8, goldfish: 8, perfumes: 8},
    {goldfish: 3, akitas: 2, perfumes: 6},
    {cats: 7, trees: 0, vizslas: 1},
    {perfumes: 7, cars: 7, akitas: 7},
    {goldfish: 0, vizslas: 0, samoyeds: 2},
    {vizslas: 2, children: 2, cats: 3},
    {vizslas: 2, pomeranians: 9, samoyeds: 3},
    {cats: 1, akitas: 3, vizslas: 1},
    {pomeranians: 10, trees: 2, goldfish: 7},
    {samoyeds: 5, trees: 7, perfumes: 4},
    {perfumes: 10, cars: 1, pomeranians: 3},
    {trees: 6, goldfish: 1, cars: 0},
    {cars: 6, samoyeds: 4, pomeranians: 5},
    {goldfish: 3, vizslas: 3, akitas: 3},
    {children: 5, cats: 0, cars: 4},
    {goldfish: 3, perfumes: 8, pomeranians: 7},
    {samoyeds: 6, cars: 7, perfumes: 10},
    {trees: 4, cars: 2, vizslas: 7},
    {samoyeds: 10, perfumes: 9, goldfish: 6},
    {cars: 4, trees: 2, perfumes: 7},
    {akitas: 3, perfumes: 9, cars: 9},
    {akitas: 8, vizslas: 2, cats: 6},
    {trees: 5, goldfish: 7, akitas: 3},
    {perfumes: 9, cars: 8, vizslas: 2},
    {trees: 3, vizslas: 0, children: 0},
    {cars: 7, trees: 2, cats: 5},
    {vizslas: 4, cars: 10, cats: 3},
    {akitas: 10, cats: 3, samoyeds: 9},
    {trees: 7, children: 5, goldfish: 6},
    {cars: 2, perfumes: 5, cats: 7},
    {samoyeds: 5, trees: 10, goldfish: 6},
    {goldfish: 10, perfumes: 4, trees: 7},
    {vizslas: 9, trees: 9, perfumes: 0},
    {trees: 4, goldfish: 9, vizslas: 8},
    {vizslas: 3, cars: 3, trees: 2},
    {goldfish: 2, akitas: 2, trees: 2},
    {children: 1, cars: 0, vizslas: 5},
    {trees: 5, akitas: 4, goldfish: 6},
    {akitas: 3, vizslas: 7, pomeranians: 5},
    {goldfish: 10, vizslas: 3, trees: 1},
    {cars: 2, trees: 1, akitas: 0},
    {akitas: 10, vizslas: 6, samoyeds: 2},
    {children: 5, trees: 1, samoyeds: 9},
    {perfumes: 9, trees: 6, vizslas: 1},
    {akitas: 7, pomeranians: 6, vizslas: 6},
    {cats: 7, children: 6, vizslas: 7},
    {trees: 2, vizslas: 7, samoyeds: 4},
    {goldfish: 0, samoyeds: 10, cars: 4},
    {pomeranians: 9, children: 3, vizslas: 5},
    {akitas: 8, vizslas: 4, cars: 5},
    {akitas: 0, perfumes: 2, pomeranians: 10},
    {akitas: 9, cars: 0, trees: 2},
    {vizslas: 10, goldfish: 8, akitas: 6},
    {trees: 0, cats: 6, perfumes: 2},
    {vizslas: 10, cars: 1, trees: 4},
    {goldfish: 8, perfumes: 6, cats: 3},
    {goldfish: 0, children: 1, akitas: 2},
    {pomeranians: 10, trees: 6, samoyeds: 6},
    {vizslas: 5, akitas: 4, pomeranians: 2},
    {goldfish: 7, trees: 0, akitas: 5},
    {goldfish: 4, vizslas: 5, cars: 7},
    {perfumes: 7, cats: 10, cars: 4},
    {samoyeds: 10, cars: 9, trees: 7},
    {pomeranians: 8, vizslas: 6, cars: 3},
    {cars: 4, cats: 9, akitas: 4},
    {cars: 6, trees: 2, perfumes: 6},
    {goldfish: 1, cats: 2, perfumes: 4},
    {akitas: 6, cats: 5, cars: 8},
    {cats: 4, vizslas: 9, akitas: 0},
    {children: 8, samoyeds: 9, trees: 4},
    {vizslas: 2, samoyeds: 10, perfumes: 7},
    {goldfish: 7, pomeranians: 4, akitas: 10},
    {perfumes: 8, cats: 4, akitas: 10},
    {trees: 0, cars: 9, goldfish: 3},
    {trees: 5, samoyeds: 7, perfumes: 8},
    {cars: 4, perfumes: 2, goldfish: 0},
    {vizslas: 4, pomeranians: 7, akitas: 1},
    {akitas: 4, goldfish: 3, perfumes: 0},
    {samoyeds: 3, akitas: 10, vizslas: 0},
    {goldfish: 1, akitas: 7, vizslas: 6},
    {perfumes: 1, goldfish: 1, pomeranians: 8},
    {children: 5, cars: 4, cats: 4},
    {vizslas: 5, cars: 10, cats: 3},
    {trees: 2, goldfish: 3, cars: 1},
    {trees: 10, goldfish: 6, perfumes: 2},
    {akitas: 5, trees: 6, cats: 3},
    {cars: 10, children: 8, goldfish: 0},
    {cats: 2, akitas: 0, pomeranians: 4},
    {perfumes: 1, vizslas: 3, cars: 3},
    {samoyeds: 8, cats: 5, perfumes: 8},
    {cars: 5, akitas: 10, trees: 2},
    {vizslas: 9, akitas: 9, cars: 3},
    {cars: 3, perfumes: 1, pomeranians: 9},
    {akitas: 1, cars: 4, perfumes: 0},
    {perfumes: 8, vizslas: 2, trees: 6},
    {pomeranians: 5, akitas: 9, cats: 8},
    {pomeranians: 8, vizslas: 3, goldfish: 10},
    {trees: 2, pomeranians: 0, goldfish: 6},
    {cats: 5, akitas: 7, goldfish: 6},
    {goldfish: 6, children: 4, trees: 10},
    {children: 1, trees: 3, akitas: 7},
    {trees: 2, samoyeds: 10, goldfish: 3},
    {samoyeds: 10, cats: 0, goldfish: 0},
    {perfumes: 3, children: 6, pomeranians: 1},
    {cars: 10, pomeranians: 1, samoyeds: 5},
    {samoyeds: 9, pomeranians: 7, perfumes: 6},
    {goldfish: 6, trees: 8, perfumes: 9},
    {samoyeds: 10, pomeranians: 9, children: 10},
    {perfumes: 3, goldfish: 7, cars: 9},
    {cats: 3, children: 4, samoyeds: 8},
    {trees: 0, cars: 10, vizslas: 10},
    {pomeranians: 10, children: 8, perfumes: 2},
    {cars: 5, vizslas: 0, samoyeds: 3},
    {trees: 1, goldfish: 8, cars: 8},
    {vizslas: 0, cars: 2, perfumes: 5},
    {trees: 2, cars: 3, vizslas: 8},
    {trees: 10, children: 9, cats: 1},
    {pomeranians: 3, perfumes: 1, vizslas: 0},
    {vizslas: 0, perfumes: 6, trees: 0},
    {vizslas: 7, pomeranians: 1, akitas: 10},
    {vizslas: 8, trees: 2, cars: 10},
    {perfumes: 9, cats: 5, goldfish: 5},
    {cats: 0, akitas: 10, perfumes: 9},
    {cars: 4, akitas: 1, trees: 1},
    {cars: 4, perfumes: 5, trees: 3},
    {goldfish: 3, akitas: 5, samoyeds: 9},
    {goldfish: 7, perfumes: 5, trees: 5},
    {akitas: 4, cats: 6, cars: 8},
    {children: 6, goldfish: 10, akitas: 7},
    {akitas: 7, vizslas: 5, perfumes: 10},
    {children: 7, vizslas: 10, akitas: 10},
    {goldfish: 6, akitas: 7, trees: 2},
    {vizslas: 6, trees: 1, akitas: 2},
    {cars: 5, vizslas: 3, akitas: 7},
    {vizslas: 4, cats: 8, perfumes: 7},
    {akitas: 3, trees: 0, children: 2},
    {cats: 7, cars: 3, children: 9},
    {trees: 10, vizslas: 3, goldfish: 7},
    {perfumes: 0, goldfish: 7, akitas: 4},
    {cats: 6, cars: 7, vizslas: 0},
    {vizslas: 4, perfumes: 6, goldfish: 5},
    {pomeranians: 8, trees: 1, akitas: 9},
    {goldfish: 7, pomeranians: 6, samoyeds: 9},
    {perfumes: 10, cars: 1, trees: 8},
    {trees: 0, goldfish: 9, children: 6},
    {trees: 1, cars: 6, pomeranians: 8},
    {perfumes: 9, cars: 0, vizslas: 10},
    {samoyeds: 4, akitas: 1, vizslas: 9},
    {perfumes: 0, trees: 2, cars: 4},
    {akitas: 0, perfumes: 5, samoyeds: 4},
    {akitas: 8, vizslas: 6, children: 2},
    {children: 1, trees: 8, goldfish: 10},
    {pomeranians: 4, trees: 10, cars: 9},
    {perfumes: 5, vizslas: 5, akitas: 4},
    {trees: 1, akitas: 10, vizslas: 6},
    {samoyeds: 0, goldfish: 9, perfumes: 7},
    {goldfish: 7, samoyeds: 10, trees: 1},
    {samoyeds: 0, pomeranians: 10, vizslas: 6},
    {children: 2, cars: 10, samoyeds: 2},
    {trees: 2, goldfish: 8, cars: 0},
    {samoyeds: 4, goldfish: 9, trees: 2},
    {trees: 8, akitas: 10, perfumes: 3},
    {samoyeds: 9, goldfish: 2, cars: 1},
    {akitas: 2, perfumes: 8, trees: 2},
    {children: 3, goldfish: 6, perfumes: 5},
    {akitas: 8, perfumes: 2, samoyeds: 6},
    {vizslas: 10, akitas: 4, pomeranians: 3},
    {cats: 8, perfumes: 3, trees: 4},
    {cars: 2, children: 4, pomeranians: 8},
    {pomeranians: 4, samoyeds: 2, goldfish: 4},
    {perfumes: 6, cars: 4, goldfish: 4},
    {akitas: 0, goldfish: 7, perfumes: 5},
    {perfumes: 4, cars: 3, akitas: 5},
    {trees: 0, vizslas: 0, goldfish: 1},
    {perfumes: 4, vizslas: 2, cars: 7},
    {goldfish: 7, pomeranians: 8, trees: 0},
    {goldfish: 7, children: 9, trees: 3},
    {akitas: 1, vizslas: 10, trees: 2},
    {perfumes: 2, cars: 4, goldfish: 10},
    {pomeranians: 6, vizslas: 9, trees: 1},
    {cars: 9, trees: 0, goldfish: 0},
    {trees: 1, goldfish: 1, vizslas: 8},
    {goldfish: 7, samoyeds: 8, children: 2},
    {children: 1, cats: 7, vizslas: 8},
    {cats: 2, pomeranians: 6, goldfish: 4},
    {perfumes: 7, cats: 3, vizslas: 6},
    {akitas: 4, samoyeds: 5, cars: 2},
    {akitas: 3, perfumes: 3, cats: 9},
    {perfumes: 10, akitas: 6, trees: 0},
    {cars: 5, children: 9, perfumes: 8},
    {vizslas: 10, cars: 3, perfumes: 5},
    {children: 9, perfumes: 1, cars: 10},
    {akitas: 0, goldfish: 8, trees: 3},
    {cars: 7, akitas: 8, children: 3},
    {cars: 4, akitas: 9, cats: 0},
    {perfumes: 4, samoyeds: 5, goldfish: 6},
    {perfumes: 10, akitas: 1, cars: 7},
    {trees: 1, goldfish: 3, vizslas: 6},
    {goldfish: 8, pomeranians: 6, trees: 10},
    {akitas: 5, vizslas: 8, goldfish: 10},
    {cats: 5, trees: 4, samoyeds: 0},
    {perfumes: 8, cars: 0, cats: 3},
    {akitas: 1, trees: 10, vizslas: 2},
    {vizslas: 6, akitas: 3, children: 10},
    {perfumes: 7, trees: 9, goldfish: 8},
    {children: 6, vizslas: 4, perfumes: 5},
    {vizslas: 6, akitas: 8, perfumes: 9},
    {goldfish: 8, cars: 4, trees: 10},
    {pomeranians: 8, cars: 5, vizslas: 0},
    {cats: 10, goldfish: 7, akitas: 1},
    {cats: 2, children: 1, cars: 6},
    {perfumes: 3, samoyeds: 6, cars: 0},
    {samoyeds: 10, pomeranians: 6, trees: 2},
    {children: 2, perfumes: 2, pomeranians: 4},
    {cats: 1, perfumes: 5, vizslas: 9},
    {vizslas: 5, perfumes: 2, akitas: 7},
    {samoyeds: 8, goldfish: 6, cats: 1},
    {goldfish: 10, perfumes: 9, cars: 4},
    {samoyeds: 0, cars: 4, vizslas: 4},
    {trees: 2, cars: 7, akitas: 8},
    {vizslas: 3, perfumes: 5, goldfish: 1},
    {cats: 7, cars: 4, trees: 1},
    {vizslas: 8, akitas: 3, goldfish: 0},
    {cars: 6, cats: 3, perfumes: 2},
    {goldfish: 1, children: 9, vizslas: 3},
    {pomeranians: 5, vizslas: 1, cars: 10},
    {children: 5, perfumes: 5, cats: 1},
    {perfumes: 2, goldfish: 7, trees: 6},
    {akitas: 2, goldfish: 4, perfumes: 10},
    {samoyeds: 3, goldfish: 0, akitas: 1},
    {trees: 8, vizslas: 9, goldfish: 0},
    {goldfish: 8, samoyeds: 0, trees: 0},
    {perfumes: 7, cars: 5, trees: 0},
    {vizslas: 3, pomeranians: 2, perfumes: 5},
    {cars: 5, perfumes: 5, akitas: 5},
    {children: 8, trees: 1, pomeranians: 4},
    {pomeranians: 0, akitas: 1, vizslas: 8},
    {akitas: 10, perfumes: 10, samoyeds: 8},
    {perfumes: 6, vizslas: 4, cats: 6},
    {children: 6, pomeranians: 5, samoyeds: 4},
    {vizslas: 1, trees: 5, akitas: 1},
    {vizslas: 10, perfumes: 10, pomeranians: 3},
    {samoyeds: 3, trees: 2, cars: 5},
    {cats: 6, children: 3, perfumes: 0},
    {pomeranians: 10, cats: 3, vizslas: 5}
];

const antSue = {
    children: 3,
    cats: 7,
    samoyeds: 2,
    pomeranians: 3,
    akitas: 0,
    vizslas: 0,
    goldfish: 5,
    trees: 3,
    cars: 2,
    perfumes: 1
};

function day16() {
    let ant = 0;
    let antTwo = 0;
    day16Arr.forEach((object, i) => {
        let correctAnt = true;
        let correctAntTwo = true;
        for (const key in object) {
            if (Object.hasOwnProperty.call(object, key)) {
                for (const keyTwo in antSue) {
                    if (Object.hasOwnProperty.call(antSue, keyTwo)) {
                        if (key == keyTwo) {
                            switch (key) {
                                case "children":
                                    if (object.children != antSue.children) {
                                        correctAnt = false;
                                        correctAntTwo = false;
                                    }
                                    break;
                                case "cats":
                                    if (object.cats != antSue.cats) {
                                        correctAnt = false;
                                    }
                                    if (object.cats <= antSue.cats) {
                                        correctAntTwo = false;
                                    }
                                    break;
                                case "samoyeds":
                                    if (object.samoyeds != antSue.samoyeds) {
                                        correctAnt = false;
                                        correctAntTwo = false;
                                    }
                                    break;
                                case "pomeranians":
                                    if (object.pomeranians != antSue.pomeranians) {
                                        correctAnt = false;
                                    }
                                    if (object.pomeranians >= antSue.pomeranians) {
                                        correctAntTwo = false;
                                    }
                                    break;
                                case "akitas":
                                    if (object.akitas != antSue.akitas) {
                                        correctAnt = false;
                                        correctAntTwo = false;
                                    }
                                    break;
                                case "vizslas":
                                    if (object.vizslas != antSue.vizslas) {
                                        correctAnt = false;
                                        correctAntTwo = false;
                                    }
                                    break;
                                case "goldfish":
                                    if (object.goldfish != antSue.goldfish) {
                                        correctAnt = false;
                                    }
                                    if (object.goldfish >= antSue.goldfish) {
                                        correctAntTwo = false;
                                    }
                                    break;
                                case "trees":
                                    if (object.trees != antSue.trees) {
                                        correctAnt = false;
                                    }
                                    if (object.trees <= antSue.trees) {
                                        correctAntTwo = false;
                                    }
                                    break;
                                case "cars":
                                    if (object.cars != antSue.cars) {
                                        correctAnt = false;
                                        correctAntTwo = false;
                                    }
                                    break;
                                case "perfumes":
                                    if (object.perfumes != antSue.perfumes) {
                                        correctAnt = false;
                                        correctAntTwo = false;
                                    }
                                    break;
                                default:
                                    break;
                            }
                        }
                    }
                }
            }
        }
        if (correctAnt) {
            ant = (i + 1);
        }
        if (correctAntTwo) {
            antTwo = (i + 1);
        }
    });

    return [ant, antTwo];
}

console.log(`Part one's answer is: ${day16()[0]}`);
console.log(`Part two's answer is: ${day16()[1]}`);